### ISSUE TITLE
não adiciona e atualiza o status do envio e código de rastreamento

### ISSUE THREAD

**Issue by thadeu220** [melhorenvio/wp-melhorenvio-v2#27]
deveria ser possível que, ao adicionar uma etiqueta, ou se ela for comprada automaticamrnte, seja adicionado novos status como aguardando embalagem do produto, aguardando envio/postagem, postado, e produto entregue, no backend do woocommerce.
assim, a situação de um pedido seria melhor acompanhada...
e, ao comprar um produto, o código de rastreio já deveria ser enviado ao cliente, bem como também ao ser entregue, o pedido deveria marcar no woocommerce como entregue!
senão fica impossível usar uma integração, e isso deveria vir nativo do app melhor envio.
não adianta querer usar ERP, pois, isso deveria ser oferecido pelo próprio melhor envio, um feedback de estado da postagem, e ao receber, chegar a notificação no woocommerce.

e isso precisa ser utrgentemente feito!

**Comment by viniciustessmann** [comment]
Essa funcionalidade foi implementada nessa nova versão 2.7.2.

**Comment by thadeu220** [comment]
Já está disponível no diretório de atualizações do Word Press?
